JAVAC=java

all: HW4 

HW4:
	javac -cp ./ HW4.java OthelloPlayer.java OthelloRandomPlayer.java GodlikeOthelloPlayer.java OthelloRandomPlayer.java OthelloState.java Test.java OthelloMove.java

clean:
	rm *.class;
